### ISSUE TITLE
Only shows first segment/incomplete PHP code

### ISSUE THREAD

**Issue by AGraber** [Antelox/FOPO-PHP-Deobfuscator#4]
Some files don't de-obfuscate properly. For example, it doesn't even close the php bracket, and the html that follows doesn't even show up, minding that those contain multiple echos to display info.

**Comment by Antelox** [comment]
Thanks to reporting. Can you give me some samples which I can analyze in order to find and fix the issue?

**Comment by AGraber** [comment]
OK, Thanks for dropping by on this old project by the way:

Obfuscated: https://pastebin.com/QwCmGYUD

Manual Deobfuscation by replacing "@eval"s with "echo"s multiple times get me this complete code after removing some obfuscated garbage that was at the beginning and end of the file:
https://pastebin.com/UTaD8Mvb

While the script truncates it to this:
https://pastebin.com/gWJ0kQYP

Thanks!

**Comment by Antelox** [comment]
Hi, sorry for delay, busy days here!
Can you test the script below with more PHP obfuscated codes, please? The truncated print should be fixed now.

https://glot.io/snippets/efruafhnez

I will look around to receive feedback from your side.

**Comment by AGraber** [comment]
Well man, seems it did the work! Thank you very much!
